export const LOADED_MODELS = 'LOADED_MODELS';
export const LOADED_WORD = 'LOADED_WORD';
export const AUTH_SCREEN_ACTIVE = 'AUTH_SCREEN_ACTIVE';
export const TOGGLE_AUTH_SCREEN_ACTIVE = 'TOGGLE_AUTH_SCREEN_ACTIVE';
